---
# tasks file for common
- name: 'Establecer nombre de host'
  hostname:
    name: "{{ nombre_dominio }}"
    use: systemd
  tags: common

#- name: 'Establecer IP interna'
#  set_fact:
#    ip_interna: "{{ ansible_facts['default_ipv4']['address'] }}"
#  tags: common

#- debug:
#    var: ip_interna
#  tags: common

- name: 'Generar fichero /etc/hosts'
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    mode: '0644'
  tags: common

- name: 'Actualizar rpms'
  dnf:
    name: '*'
    state: latest
  notify: Reinicio #handler
  tags: common

- name: 'Instalar rpms'
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ rpms }}"
  tags: common

- name: 'Habilitar servicios necesarios'
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ servicios }}"
  tags: common

- name: 'Set timezone to Europe/Madrid'
# zone:
  timezone:
    name: Europe/Madrid
  tags: common

- name: 'Deshabilitar SELinux'
  selinux:
    state: disabled
  when: not enforcing_selinux
  notify: Reinicio
  tags: common