---
# tasks file for App
- name: 'Creamos el directorio "/tmp/despliegueApp"'
  file:
    path: "{{ pathDespliegue }}"
    state: directory
  tags: App

- name: 'Obtenemos los ficheros necesarios para el despliegue'
  copy:
    src: ../files/{{ item }}.yaml
    dest: "{{ pathDespliegue }}"
  with_items:
    - nfs-pv
    - nfs-pvc
    - webapp-volumes
  tags: App

- name: 'Creamos el namespace'
  shell: | 
    kubectl create namespace webapp-volumes
  tags: App

- name: 'Definimos el persistent volume'
  shell: |
    kubectl apply -f {{ pathDespliegue }}/nfs-pv.yaml
    kubectl get pv --namespace=webapp-volumes
    kubectl describe pv --namespace=webapp-volumes
  register: pvOut
  tags: App

- debug: var=pvOut.stdout_lines
  tags: App

- name: 'Creamos el claim'
  shell: |
    kubectl apply -f {{ pathDespliegue }}/nfs-pvc.yaml
    kubectl get pvc --namespace=webapp-volumes
    kubectl describe pvc nfs-pvc --namespace=webapp-volumes
  register: pvcOut
  tags: App

- debug: var=pvcOut.stdout_lines
  tags: App

- name: 'Realizamos el deployment'
  shell: |
    kubectl apply -f {{ pathDespliegue }}/webapp-volumes.yaml
    kubectl get pods --namespace=webapp-volumes -o wide
    kubectl get svc --namespace=webapp-volumes -o wide
    kubectl describe svc volumes-service --namespace=webapp-volumes
    kubectl get ep --namespace=webapp-volumes -o wide
    kubectl describe ep volumes-service --namespace=webapp-volumes
  register: deploymentOut
  tags: App

- debug: var=deploymentOut.stdout_lines
  tags: App

- name: 'Borramos el directorio con los ficheros'
  file:
    path: "{{ pathDespliegue }}"
    state: absent
  tags: App