- name: 'Kubernetes, NFS, SDN, HAProxy'
  hosts: all
  remote_user: azureuser
  gather_facts: true
  become: true
  tasks:
    - name: 'Ejecucion de tareas comunes'
      include_role:
        name: common
      tags: common

- name: 'Config kubernetes Master'
  hosts: Master
  remote_user: azureuser
  become: true
  tasks:
    - name: 'kubernetes Master'
      include_role:
         name: Master
      tags: kubernetesM

- name: 'Config kubernetes Worker'
  hosts: Worker
  remote_user: azureuser
  become: true
  tasks:
    - name: 'kubernetes Worker'
      include_role:
         name: Worker
      tags: kubernetesW

- name: 'Config NFS'
  hosts: NFS
  remote_user: azureuser
  become: true
  tasks:
    - name: 'NFS'
      include_role:
         name: NFS
      tags: NFS

- name: 'Config SDN'
  hosts: Master
  remote_user: azureuser
  become: true
  tasks:
    - name: 'SDN'
      include_role:
         name: Master
      tags: SDN

- name: 'Config HAProxy'
  hosts: Master
  remote_user: azureuser
  become: true
  tasks:
    - name: 'HAProxy'
      include_role:
         name: Master
      tags: HAProxy

#- name: 'Config App'
#  hosts: App
#  remote_user: azureuser
#  become: true
#  tasks:
#    - name: 'App'
#      include_role:
#         name: Worker
#      tags: App